export type Product = {
  id: string;
  name: string;
  details: string;
  rating: number;
  numRatings: number;
  price: number;
  discountedPrice?: number;
  styles?: string[]; // colours
  inStock: boolean;
  discounted: boolean;
  images: number[]; // multiple product images

  // for filtering
  category: string;
  type?: string;
  material?: string[];
};

export const MockProducts: Product[] = [
  {
    id: "0",
    name: "Urban Loft Sofa",
    details:
      "A sleek, modular with tufted cushions and low-profile arms—perfect for modern living rooms.",
    rating: 4.5,
    numRatings: 207,
    price: 1499.99,
    discountedPrice: 1299.99,
    styles: ["Grey", "Beige", "Charcoal"],
    inStock: true,
    discounted: true,
    images: [1, 2, 3, 4, 5],
    category: "Sofas and Couches",
    type: "Sectional",
    material: ["Fabric", "Wood"],
  },
  {
    id: "1",
    name: "Scandinavian Velvet Loveseat",
    details:
      "Compact two-seater loveseat wrapped in plush velvet with slim wooden legs for an airy feel.",
    rating: 4.2,
    numRatings: 98,
    discountedPrice: 649.99,
    price: 899.99,
    discounted: true,
    styles: ["Blue", "Green", "Mustard"],
    inStock: true,
    images: [1, 2, 3],
    category: "Sofas and Couches",
    type: "Loveseat",
    material: ["Velvet", "Wood"],
  },
  {
    id: "2",
    name: "Convertible Sofa Bed",
    details:
      "Transforms effortlessly from a cozy sofa to a full-size bed—ideal for guest rooms and studios.",
    rating: 4.0,
    numRatings: 152,
    price: 1199.99,
    discountedPrice: 1049.99,
    styles: ["Grey", "Navy"],
    inStock: true,
    discounted: true,
    images: [1, 2, 3],
    category: "Sofas and Couches",
    type: "Sofabed",
    material: ["Fabric", "Metal"],
  },
  {
    id: "3",
    name: "Mid-Century Modern Armchair",
    details:
      "Classic armchair with angled wooden frame and tufted upholstery—timeless elegance for any corner.",
    rating: 4.7,
    numRatings: 324,
    price: 499.99,
    discounted: false,
    styles: ["Green", "Orange", "Brown"],
    inStock: true,
    images: [1, 2],
    category: "Sofas and Couches",
    type: "Armchair",
    material: ["Fabric", "Wood"],
  },
  {
    id: "4",
    name: "Vintage Leather 3-Seater Sofa",
    details:
      "Rich genuine leather sofa with deep seating and rolled arms—ages beautifully over time.",
    rating: 4.3,
    numRatings: 178,
    price: 1799.99,
    discountedPrice: 1599.99,
    styles: ["Brown", "Black"],
    inStock: true,
    discounted: true,
    images: [1, 2, 3],
    category: "Sofas and Couches",
    type: "3-Seater",
    material: ["Leather", "Wood"],
  },
  {
    id: "5",
    name: "Compact Apartment Sectional",
    details:
      "Space-saving L-shaped sectional designed for small spaces—fabric upholstery and hidden storage.",
    rating: 4.1,
    numRatings: 89,
    price: 1399.99,
    discounted: false,
    styles: ["Beige", "Grey"],
    inStock: true,
    images: [1, 2, 3],
    category: "Sofas and Couches",
    type: "Sectional",
    material: ["Fabric", "Wood"],
  },
  {
    id: "6",
    name: "Reclining Power Loveseat",
    details:
      "Enjoy ultimate comfort with power reclining feature, built-in USB ports, and plush padding.",
    rating: 4.4,
    numRatings: 210,
    price: 1299.99,
    discountedPrice: 1149.99,
    styles: ["Black", "Brown"],
    inStock: true,
    discounted: true,
    images: [1, 2, 3, 4],
    category: "Sofas and Couches",
    type: "Loveseat",
    material: ["Leather", "Metal"],
  },
  {
    id: "7",
    name: "Convertible Chaise Sectional",
    details:
      "Chaise lounge attached to a sectional—reversible design for right or left orientation.",
    rating: 4.6,
    numRatings: 142,
    price: 1599.99,
    discounted: false,
    styles: ["Grey", "Cream"],
    inStock: true,
    images: [1, 2, 3],
    category: "Sofas and Couches",
    type: "Sectional",
    material: ["Fabric", "Wood"],
  },
  {
    id: "8",
    name: "Roll-Out Guest Sofa",
    details:
      "Hidden pull-out bed under clean-lined sofa; perfect for overnight guests without sacrificing style.",
    rating: 3.9,
    numRatings: 65,
    price: 1099.99,
    discounted: false,
    styles: ["Blue", "Grey"],
    inStock: true,
    images: [1, 2],
    category: "Sofas and Couches",
    type: "Sofabed",
    material: ["Fabric", "Metal"],
  },
  {
    id: "9",
    name: "Classic Tuxedo Sofa",
    details:
      "High back and track arms in a single, elegant line; tailored for formal living rooms and offices.",
    rating: 4.8,
    numRatings: 276,
    price: 1699.99,
    discountedPrice: 1499.99,
    styles: ["Navy", "Charcoal"],
    inStock: true,
    discounted: true,
    images: [1, 2, 3, 4],
    category: "Sofas and Couches",
    type: "3-Seater",
    material: ["Fabric", "Wood"],
  },

  // Tables and Chairs
  {
    id: "10",
    name: "Marble Top Dining Table",
    details:
      "Elegant round dining table with genuine marble surface and solid wood pedestal base.",
    rating: 4.6,
    numRatings: 154,
    price: 1199.99,
    discounted: false,
    styles: ["White", "Black"],
    inStock: true,
    images: [1, 2, 3],
    category: "Tables and Chairs",
    type: "Dining Table",
    material: ["Wood", "Stone"],
  },
  {
    id: "11",
    name: "Industrial Metal Coffee Table",
    details:
      "Sturdy coffee table with reclaimed wood top and matte black metal frame for an edgy look.",
    rating: 4.3,
    numRatings: 98,
    price: 399.99,
    discountedPrice: 349.99,
    styles: ["Brown", "Black"],
    inStock: true,
    discounted: true,
    images: [1, 2],
    category: "Tables and Chairs",
    type: "Coffee Table",
    material: ["Wood", "Metal"],
  },
  {
    id: "12",
    name: "Set of 4 Upholstered Dining Chairs",
    details:
      "Comfortable fabric seats with tapered wooden legs—perfect blend of style and functionality.",
    rating: 4.4,
    numRatings: 123,
    price: 599.99,
    discounted: false,
    styles: ["Grey", "Beige"],
    inStock: true,
    images: [1, 2, 3],
    category: "Tables and Chairs",
    type: "Chair",
    material: ["Fabric", "Wood"],
  },
  {
    id: "13",
    name: "Acrylic Bar Stools (Set of 2)",
    details:
      "Clear acrylic seats with chrome footrest—lightweight and modern for kitchen islands or bars.",
    rating: 4.1,
    numRatings: 67,
    price: 299.99,
    discounted: false,
    styles: ["Clear"],
    inStock: true,
    images: [1, 2],
    category: "Tables and Chairs",
    type: "Stool",
    material: ["Plastic", "Metal"],
  },
  {
    id: "14",
    name: "Live Edge Wood Bench",
    details:
      "Organic-shaped bench featuring natural wood grain and live-edge detailing on steel legs.",
    rating: 4.7,
    numRatings: 89,
    price: 499.99,
    discountedPrice: 449.99,
    styles: ["Brown"],
    inStock: true,
    discounted: true,
    images: [1, 2],
    category: "Tables and Chairs",
    type: "Bench",
    material: ["Wood", "Metal"],
  },
  {
    id: "15",
    name: "Glass Top Side Table",
    details:
      "Minimalist side table with tempered glass surface and brushed metal frame for a sleek profile.",
    rating: 4.2,
    numRatings: 76,
    price: 249.99,
    discounted: false,
    styles: ["Clear", "Silver"],
    inStock: true,
    images: [1, 2, 3],
    category: "Tables and Chairs",
    type: "Coffee Table",
    material: ["Glass", "Metal"],
  },
  {
    id: "16",
    name: "Rustic Farmhouse Dining Table",
    details:
      "Hand-scraped pine top with whitewashed finish and turned legs—charming country style.",
    rating: 4.5,
    numRatings: 112,
    price: 999.99,
    discountedPrice: 899.99,
    styles: ["White", "Brown"],
    inStock: true,
    discounted: true,
    images: [1, 2, 3],
    category: "Tables and Chairs",
    type: "Dining Table",
    material: ["Wood"],
  },
  {
    id: "17",
    name: "Stackable Metal Chairs (Set of 4)",
    details:
      "Lightweight perforated metal seating—perfect for patios and easy storage when not in use.",
    rating: 4.0,
    numRatings: 54,
    price: 329.99,
    discounted: false,
    styles: ["White", "Black"],
    inStock: true,
    images: [1, 2],
    category: "Tables and Chairs",
    type: "Chair",
    material: ["Metal"],
  },
  {
    id: "18",
    name: "Adjustable Height Coffee Table",
    details:
      "Lift-top table converts to laptop desk or dining surface—versatile and compact design.",
    rating: 4.3,
    numRatings: 98,
    price: 449.99,
    discounted: false,
    styles: ["Brown", "Grey"],
    inStock: true,
    images: [1, 2, 3],
    category: "Tables and Chairs",
    type: "Coffee Table",
    material: ["Wood", "Metal"],
  },
  {
    id: "19",
    name: "Minimalist Folding Chair",
    details:
      "Slim folding frame with molded plastic seat—ideal for extra seating and easy storage.",
    rating: 4.1,
    numRatings: 63,
    price: 79.99,
    discounted: false,
    styles: ["White", "Beige"],
    inStock: true,
    images: [1, 2],
    category: "Tables and Chairs",
    type: "Chair",
    material: ["Plastic", "Metal"],
  },

  // Office
  {
    id: "20",
    name: "Ergonomic Mesh Office Chair",
    details:
      "Adjustable lumbar support, breathable mesh back, and tilt function for all-day comfort.",
    rating: 4.6,
    numRatings: 210,
    price: 299.99,
    discountedPrice: 249.99,
    styles: ["Black", "Grey"],
    inStock: true,
    discounted: true,
    images: [1, 2, 3],
    category: "Office",
    type: "Chair",
    material: ["Mesh", "Metal"],
  },
  {
    id: "21",
    name: "L-Shaped Computer Desk",
    details:
      "Spacious corner desk with cable management and adjustable height legs for ergonomic setup.",
    rating: 4.4,
    numRatings: 145,
    price: 499.99,
    discounted: false,
    styles: ["White", "Oak"],
    inStock: true,
    images: [1, 2, 3],
    category: "Office",
    type: "Desk",
    material: ["Wood", "Metal"],
  },
  {
    id: "22",
    name: "Industrial Steel Shelving Unit",
    details:
      "Heavy-duty open shelving with powder-coated finish—perfect for office storage and displays.",
    rating: 4.2,
    numRatings: 88,
    price: 399.99,
    discounted: false,
    styles: ["Black", "Grey"],
    inStock: true,
    images: [1, 2],
    category: "Office",
    type: "Shelving",
    material: ["Metal"],
  },
  {
    id: "23",
    name: "Executive Wood Desk",
    details:
      "Classic solid wood desk with file drawers and leather inlay—adds elegance to any home office.",
    rating: 4.7,
    numRatings: 132,
    price: 899.99,
    discountedPrice: 799.99,
    styles: ["Brown", "Walnut"],
    inStock: true,
    discounted: true,
    images: [1, 2, 3],
    category: "Office",
    type: "Desk",
    material: ["Wood"],
  },
  {
    id: "24",
    name: "Adjustable Monitor Arm",
    details:
      "Articulating arm with gas spring for height and tilt adjustments—improves ergonomics and desk space.",
    rating: 4.5,
    numRatings: 76,
    price: 149.99,
    discounted: false,
    styles: ["Black", "Silver"],
    inStock: true,
    images: [1, 2],
    category: "Office",
    type: "Organisation",
    material: ["Metal"],
  },
  {
    id: "25",
    name: "Rolling File Cabinet",
    details:
      "Mobile two-drawer file cabinet with lock and casters—keeps documents secure and accessible.",
    rating: 4.3,
    numRatings: 58,
    price: 229.99,
    discounted: false,
    styles: ["White", "Black"],
    inStock: true,
    images: [1, 2],
    category: "Office",
    type: "Organisation",
    material: ["Metal"],
  },
  {
    id: "26",
    name: "Standing Height Desk Converter",
    details:
      "Desktop riser lifts monitors and keyboard to standing height—promotes healthier posture.",
    rating: 4.0,
    numRatings: 94,
    price: 199.99,
    discounted: false,
    styles: ["Black", "Grey"],
    inStock: true,
    images: [1, 2],
    category: "Office",
    type: "Desk",
    material: ["Metal", "Wood"],
  },
  {
    id: "27",
    name: "Executive Leather Office Chair",
    details:
      "Luxurious high-back chair with padded armrests and premium PU leather upholstery.",
    rating: 4.4,
    numRatings: 120,
    price: 349.99,
    discountedPrice: 299.99,
    styles: ["Black", "Brown"],
    inStock: true,
    discounted: true,
    images: [1, 2, 3],
    category: "Office",
    type: "Chair",
    material: ["Leather", "Metal"],
  },
  {
    id: "28",
    name: "Corner Bookshelf Organizer",
    details:
      "Tall corner unit with adjustable shelves—optimizes small office spaces with vertical storage.",
    rating: 4.1,
    numRatings: 67,
    price: 179.99,
    discounted: false,
    styles: ["White", "Oak"],
    inStock: true,
    images: [1, 2],
    category: "Office",
    type: "Shelving",
    material: ["Wood"],
  },
  {
    id: "29",
    name: "Under-Desk Cable Tray",
    details:
      "Metal wire tray mounts under desk to corral cables and power strips—keeps workspace tidy.",
    rating: 4.3,
    numRatings: 82,
    price: 49.99,
    discounted: false,
    styles: ["Black"],
    inStock: true,
    images: [1],
    category: "Office",
    type: "Organisation",
    material: ["Metal"],
  },

  // Home Decor
  {
    id: "30",
    name: "Abstract Canvas Wall Art",
    details:
      "Bold splashes of color on gallery-wrapped canvas—instantly refreshes any living space.",
    rating: 4.5,
    numRatings: 152,
    price: 199.99,
    discounted: false,
    styles: ["Multi"],
    inStock: true,
    images: [1, 2],
    category: "Home Decor",
    type: "Art",
  },
  {
    id: "31",
    name: "Ceramic Table Lamp",
    details:
      "Glazed ceramic base with linen shade—provides soft ambient lighting for bedrooms and offices.",
    rating: 4.3,
    numRatings: 88,
    price: 89.99,
    discountedPrice: 74.99,
    styles: ["White", "Blue"],
    inStock: true,
    discounted: true,
    images: [1, 2, 3],
    category: "Home Decor",
    type: "Light",
  },
  {
    id: "32",
    name: "Indoor Fiddle Leaf Fig Tree",
    details:
      "Lifelike faux plant in a woven basket—adds greenery with zero maintenance required.",
    rating: 4.7,
    numRatings: 210,
    price: 129.99,
    discounted: false,
    styles: ["Green"],
    inStock: true,
    images: [1, 2],
    category: "Home Decor",
    type: "Plant",
  },
  {
    id: "33",
    name: "Set of 3 Decorative Vases",
    details:
      "Ceramic vases in graduated heights and matte finish—ideal for minimalist or boho interiors.",
    rating: 4.2,
    numRatings: 67,
    price: 59.99,
    discounted: false,
    styles: ["White", "Beige"],
    inStock: true,
    images: [1, 2],
    category: "Home Decor",
    type: "Art",
  },
  {
    id: "34",
    name: "Geometric Wall Mirror",
    details:
      "Brass-framed hexagonal mirror—brings modern elegance and light to entryways and living rooms.",
    rating: 4.4,
    numRatings: 120,
    price: 149.99,
    discounted: false,
    styles: ["Gold"],
    inStock: true,
    images: [1, 2],
    category: "Home Decor",
    type: "Art",
  },
  {
    id: "35",
    name: "LED Floor Lamp",
    details:
      "Slim arc lamp with adjustable head and energy-efficient LED—perfect for reading nooks.",
    rating: 4.6,
    numRatings: 98,
    price: 179.99,
    discountedPrice: 159.99,
    styles: ["Black", "White"],
    inStock: true,
    discounted: true,
    images: [1, 2],
    category: "Home Decor",
    type: "Light",
  },
  {
    id: "36",
    name: "Macrame Wall Hanging",
    details:
      "Handwoven cotton macrame with wooden dowel—adds texture and bohemian charm to any wall.",
    rating: 4.5,
    numRatings: 80,
    price: 49.99,
    discounted: false,
    styles: ["Natural"],
    inStock: true,
    images: [1, 2],
    category: "Home Decor",
    type: "Art",
  },
  {
    id: "37",
    name: "Scented Soy Candle Set",
    details:
      "Pack of three candles (lavender, vanilla, eucalyptus) in glass jars—long-lasting, clean burn.",
    rating: 4.8,
    numRatings: 145,
    price: 39.99,
    discounted: false,
    styles: ["Multi"],
    inStock: true,
    images: [1],
    category: "Home Decor",
    type: "Art",
  },
  {
    id: "38",
    name: "Decorative Throw Pillow",
    details:
      "Soft linen pillow with geometric embroidery—mix-and-match for living room or bedroom accents.",
    rating: 4.3,
    numRatings: 110,
    price: 29.99,
    discounted: false,
    styles: ["Grey", "Blue", "Mustard"],
    inStock: true,
    images: [1, 2],
    category: "Home Decor",
    type: "Art",
  },
  {
    id: "39",
    name: "Floating Wall Shelf",
    details:
      "Solid pine wood shelf with invisible mounting hardware—showcase photos, books, and plants.",
    rating: 4.4,
    numRatings: 76,
    price: 59.99,
    discounted: false,
    styles: ["Natural", "White"],
    inStock: true,
    images: [1, 2],
    category: "Home Decor",
    type: "Organisation",
  },
];
